name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Use 'pip install' without specifying the virtual env path, which is generally fine 
          # in the GitHub Actions runner environment.
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          # 💡 FIX: Run pytest using the 'python -m' flag
          # This tells Python to run the 'pytest' module directly, 
          # which is guaranteed to be in the path after 'pip install'.
          python -m pytest -q
